@startuml  

left to right direction  
skinparam packageStyle rectangle  
skinparam linetype ortho   

actor "Cicloturista" as User  
actor "Admin Piattaforma" as Admin 

rectangle "Area Personale & Itinerari" {  

    usecase "RF1 - Login Utente" as RF1  
    usecase "RF6 - Creazione itinerari" as RF6  
    usecase "RF11 - Gestione itinerari privati" as RF11  
    usecase "RF10 - Pubblicazione itinerario" as RF10  
    usecase "RF12 - Copia itinerario" as RF12  
    usecase "RF13 - Modifica Itinerario" as RF13  
    usecase "RF14 - Gestione Storico" as RF14  
    usecase "RF18 - Recording percorso" as RF18  
    usecase "RF9 - Raccolta dati (Facoltativa)" as RF9  

}  

User --> RF6  
User --> RF11  
User --> RF1 
Admin --> RF9 

' Relazioni  

RF6 ..> RF1 : <<include>>  
RF11 ..> RF1 : <<include>>  
RF10 ..> RF6 : <<extend>>  
RF18 ..> RF6 : <<extend>>  
RF12 ..> RF11 : <<extend>>  
RF13 ..> RF11 : <<extend>>  
RF14 ..> RF11 : <<extend>>  

@enduml 